Calculate cardinality estimate variance and Simulate number of active registers
world-federation-of-advertisers/planning-evaluation-framework pull request #53
Opened 2021-07-21 05:56 UTC by jiayu-google

… registers.

2021-07-21 18:32 UTC, matthewclegg requested changes

2021-07-21 18:32 UTC, matthewclegg commented on src/simulator/halo_simulator.py
> +    def _cardinality_estimate_variance(self, n: int) -> float:
Perhaps change the name to _liquid_legions_cardinality_estimate_variance?

2021-07-21 18:32 UTC, matthewclegg commented on src/simulator/halo_simulator.py
> +    def _num_active_registers(
Add documentation.  Also, perhaps this should be called _liquid_legions_num_active_regions.

2021-07-21 21:46 UTC, riemanli approved these changes
LGTM.

2021-07-26 06:09 UTC, merged

2021-07-26 19:04 UTC, uakyol commented
We are still investigating, how this PR got merged by mistake