Simulated Venn diagram reach by spend
world-federation-of-advertisers/planning-evaluation-framework pull request #68
Opened 2021-08-09 21:38 UTC by riemanli

2021-08-10 00:02 UTC, matthewclegg requested changes

2021-08-10 21:21 UTC, riemanli commented on src/simulator/halo_simulator.py
> +        # Happen when there is no active publishers, i.e. 0 spend vector.
Thanks for the suggestion. The comment is modified.

2021-08-10 21:23 UTC, riemanli commented on src/simulator/halo_simulator.py
> +              that should be allocated to reach estimation.  The remainder is
Thanks for pointing out the ambiguity. Would the following be better?
`Specifies the proportion of the privacy budget that should be allocated to the reach count in the primitive Venn diagram regions.  The remainder is allocated to the cardinality estimation from the Liquid Legions.`

2021-08-11 18:16 UTC, riemanli commented on src/simulator/halo_simulator.py
> +        # Happen when there is no active publishers, i.e. 0 spend vector.
Done.

2021-08-11 18:16 UTC, riemanli commented on src/simulator/halo_simulator.py
> +              that should be allocated to reach estimation.  The remainder is
Confirmed with Matthew and modified the docstring.

2021-08-11 22:58 UTC, jiayu-google approved these changes
This is awesome Rieman!

I learned much from your test.

2021-08-12 20:14 UTC, matthewclegg approved these changes

2021-08-12 21:31 UTC, RonPinelliMRC approved these changes
MRC approving based on cursory review after confirming non-independent code review on an exception basis. Experimental code will require independent review prior to publication of or reliance on results generated.

2021-08-12 21:42 UTC, merged